M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Thu 25 Sep 2025 09:06:53 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-09-25T21:06:53-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X4.5858Y-2.5067
X4.9008Y-2.5067
X5.887Y-2.5094
X6.202Y-2.5094
M30
